import type { Metadata } from "next";
import { greatVibes, montserrat } from "@/lib/fonts";
import "./globals.css";
import ScrollToTopButton from "@/components/ScrollToTopButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      data-theme="caferaro"
      className={`${greatVibes.variable} ${montserrat.variable}`}
    >
      <body className={`${montserrat.className} antialiased`}>
        <div className="bg-cream text-espresso">{children}</div>
        <ScrollToTopButton />
      </body>
    </html>
  );
}
